### ISSUE TITLE
Real time data sync issues

### ISSUE THREAD

**Issue by simplecrm-github** [bakwc/mysql_ch_replicator#61] opened 2024-12-19 05:46 UTC
Hi 

I have a config.yaml file configured as follows:

mysql:
  host: '172.22.5.14'
  port: 3306
  user: 'clickhouse'
  password: 'xxxxxx' 

clickhouse:
  host: 'localhost'
  port: 8123
  user: 'default'
  password: 'xxxxx' 

binlog_replicator:
  data_dir: '/binlog/'
  records_per_file: 100000

databases: 'abanscrm'
tables: ['contacts', 'contacts_cstm', 'accounts', 'accounts_cstm', 'aos_invoices', 'aos_invoices_cstm', 'prod_product_purchased_cstm', 'prod_product_purchased', 'scrm_brands', 'scrm_brands_aos_products_1_c', 'contacts_prod_product_purchased_1_c', 'aos_products', 'aos_products_cstm', 'aos_product_categories', 'aos_product_categories_cstm']

When I execute the following command to enable real-time replication:

**/usr/bin/python3.11 /usr/local/bin/mysql_ch_replicator --config /home/config.yaml run_all**

I encounter an error indicating that the replication is attempting to process a table (**user_preferences_portal**) that is not listed in the config.yaml file. Below is the error log:

[dbrepl abanscrm 2024-12-19 05:28:33,242     INFO] launched db_replicator
[dbrepl abanscrm 2024-12-19 05:28:33,257     INFO] running realtime replication from the position: ('binlog.000002', 159251553)
[dbrepl abanscrm 2024-12-19 05:28:35,097     INFO] set position to /binlog/abanscrm/9.bin
[dbrepl abanscrm 2024-12-19 05:28:35,201     INFO] found transaction ('binlog.000002', 159251553) inside /binlog/abanscrm/9.bin
[dbrepl abanscrm 2024-12-19 05:28:35,222    ERROR] unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 178, in run
    self.run_realtime_replication()
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 379, in run_realtime_replication
    self.handle_event(event)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 401, in handle_event
    event_handlers[event.event_type](event)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 482, in handle_query_event
    self.handle_create_table_query(query, event.db_name)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 491, in handle_create_table_query
    mysql_structure, ch_structure = self.converter.parse_create_table_query(query)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/converter.py", line 540, in parse_create_table_query
    mysql_table_structure = self.parse_mysql_table_structure(mysql_query)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/converter.py", line 567, in parse_mysql_table_structure
    raise Exception('wrong create statement', create_statement)
Exception: ('wrong create statement', 'CREATE TABLE  IF NOT EXISTS user_preferences_portal (\n\t\t\tid char(36) NOT NULL,\n\t\t\tcategory varchar(50) DEFAULT NULL,\n\t\t\tdeleted tinyint(1) DEFAULT 0,\n\t\t\tdate_entered datetime DEFAULT NULL,\n\t\t\tdate_modified datetime DEFAULT NULL,\n\t\t\tassigned_user_id char(36) DEFAULT NULL,\n\t\t\tcontents longtext DEFAULT NULL\n\t\t  ) ENGINE=InnoDB DEFAULT CHARSET=utf8')

How can I resolve this issue to ensure only the specified tables are included in the replication process?

**Comment by bakwc** [comment] 2024-12-19 11:01
Fixed in `0.0.46` please update and check if it helped

**Comment by simplecrm-github** [comment] 2024-12-19 12:34
We have updated the version to 0.0.46 and are now getting the following error.

/usr/bin/python3.11 /usr/local/bin/mysql_ch_replicator --config /home/settings.yaml run_all
[runner 2024-12-19 12:30:24,705     INFO] running replication for abanscrm (initial replication finished)
[runner 2024-12-19 12:30:24,706     INFO] all replicators launched
[binlogrepl 2024-12-19 12:30:25,227     INFO] state start position: ('binlog.000004', 133412003)
[binlogrepl 2024-12-19 12:30:25,227     INFO] connection_settings: {'host': '172.22.5.14', 'port': 3306, 'user': 'clickhouse', 'passwd': 'xxxxxx', 'charset': 'utf8'}
[binlogrepl 2024-12-19 12:30:25,228     INFO] resume_stream: True
[binlogrepl 2024-12-19 12:30:25,228     INFO] allowed_events_in_packet: [event, event, event, event, row_event, event, row_event, row_event, row_event, event, event, event, event, event, event, event, event, row_event, event, event, event, event, event, event]
[binlogrepl 2024-12-19 12:30:25,228     INFO] server_id: 2456079458
[binlogrepl 2024-12-19 12:30:25,229     INFO] log_pos: 133412003
[binlogrepl 2024-12-19 12:30:25,229     INFO] log_file: binlog.000004
[dbopt None 2024-12-19 12:30:25,286     INFO] running optimizer
[dbrepl abanscrm 2024-12-19 12:30:25,289     INFO] launched db_replicator
[dbrepl abanscrm 2024-12-19 12:30:25,304     INFO] running realtime replication from the position: ('binlog.000004', 16546193)
[dbrepl abanscrm 2024-12-19 12:30:25,332     INFO] set position to /binlog/abanscrm/1.bin
[dbrepl abanscrm 2024-12-19 12:30:25,361     INFO] found transaction ('binlog.000004', 16546193) inside /binlog/abanscrm/1.bin
[dbrepl abanscrm 2024-12-19 12:30:25,374     INFO] stats: {"last_transaction": ["binlog.000004", 16546768], "events_count": 1, "insert_events_count": 0, "insert_records_count": 0, "erase_events_count": 0, "erase_records_count": 0, "no_events_count": 0, "cpu_load": 3.549371403840742e-10}
**[dbrepl abanscrm 2024-12-19 12:30:28,400    ERROR] Error serializing column `warranty_start_date_c` into data type `Nullable(Date32)`**
Traceback (most recent call last):
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/driver/common.py", line 52, in write_array
    dest += buff.pack(*column)
            ^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 105, in chunk_gen
    col_type.write_column(data, output, context)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 209, in write_column
    self.write_column_data(column, dest, ctx)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 224, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/temporal.py", line 48, in _write_column_binary
    write_array(self._array_type, column, dest, ctx.column_name)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/driver/common.py", line 57, in write_array
    raise DataError(f'Unable to create Python array{col_msg}.  This is usually caused by trying to insert None ' +
**clickhouse_connect.driver.exceptions.DataError: Unable to create Python array for source column `warranty_start_date_c`.  This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable**


Kindly help with this error highlighted?

**Comment by bakwc** [comment] 2024-12-19 14:28
Could you please share a table structure with `warranty_start_date_c` column? (create sql statement, like show create table table_name)?

**Comment by simplecrm-github** [comment] 2024-12-19 16:37
Hi, iam just resharing the error.

**[dbrepl abanscrm 2024-12-19 16:35:22,493    ERROR] Error serializing column `warranty_start_date_c` into data type `Nullable(Date32)`**
Traceback (most recent call last):
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 105, in chunk_gen
    col_type.write_column(data, output, context)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 209, in write_column
    self.write_column_data(column, dest, ctx)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 224, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/temporal.py", line 45, in _write_column_binary
    column = [0 if x is None else (x - esd).days for x in column]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/clickhouse_connect/datatypes/temporal.py", line 45, in <listcomp>
    column = [0 if x is None else (x - esd).days for x in column]
                                   ~~^~~~~
**TypeError: unsupported operand type(s) for -: 'int' and 'datetime.datetime'**

**Comment by bakwc** [comment] 2024-12-20 08:53
Please enable debug logs in a `config.yaml` file:

```
..
log_level: 'info'
..
```
And attach all debug logs from the moment you starting app. Example of what should be in logs:

```
[dbrepl replication_test_db 2024-12-20 08:48:01,564    DEBUG] upload records, to insert: 0, to delete: 0
[dbrepl replication_test_db 2024-12-20 08:48:01,580    DEBUG] processing event ('binlog.000017', 51676), 3,
[dbrepl replication_test_db 2024-12-20 08:48:01,583    DEBUG] processing query event: ('binlog.000017', 51676), query: BEGIN
[dbrepl replication_test_db 2024-12-20 08:48:01,587    DEBUG] processing event ('binlog.000017', 51819), 1, test_table
[dbrepl replication_test_db 2024-12-20 08:48:01,591    DEBUG] processing insert event: ('binlog.000017', 51819), table: test_table, records: [[2, b'RAlex', None, datetime.date(2015, 6, 2), datetime.date(2015, 6, 2)]]
[dbrepl replication_test_db 2024-12-20 08:48:01,595    DEBUG] processing event ('binlog.000017', 52027), 3,
[dbrepl replication_test_db 2024-12-20 08:48:01,599    DEBUG] processing query event: ('binlog.000017', 52027), query: BEGIN
[dbrepl replication_test_db 2024-12-20 08:48:01,603    DEBUG] processing event ('binlog.000017', 52166), 1, test_table
[dbrepl replication_test_db 2024-12-20 08:48:01,608    DEBUG] processing insert event: ('binlog.000017', 52166), table: test_table, records: [[3, b'Alex', None, datetime.date(2015, 6, 2), None]]
[dbrepl replication_test_db 2024-12-20 08:48:01,613    DEBUG] processing event ('binlog.000017', 52374), 3,
[dbrepl replication_test_db 2024-12-20 08:48:01,617    DEBUG] processing query event: ('binlog.000017', 52374), query: BEGIN
[dbrepl replication_test_db 2024-12-20 08:48:01,622    DEBUG] processing event ('binlog.000017', 52538), 1, test_table
[dbrepl replication_test_db 2024-12-20 08:48:01,625    DEBUG] processing insert event: ('binlog.000017', 52538), table: test_table, records: [[4, b'Givi', datetime.datetime(2023, 1, 8, 3, 11, 9), datetime.date(2015, 6, 2), None], [5, b'Givi2', datetime.datetime(2023, 1, 8, 3, 11, 9), datetime.date(2015, 6, 2), datetime.date(1980, 3, 5)]]
[binlogrepl 2024-12-20 08:48:02,568    DEBUG] received event <class 'mysql_ch_replicator.pymysqlreplication.event.RotateEvent'>, ('binlog.000017', 52569)
[binlogrepl 2024-12-20 08:48:02,572    DEBUG] received event <class 'mysql_ch_replicator.pymysqlreplication.event.FormatDescriptionEvent'>, ('binlog.000017', 52569)
[dbrepl replication_test_db 2024-12-20 08:48:02,631    DEBUG] upload records, to insert: 2, to delete: 2
[dbrepl replication_test_db 2024-12-20 08:48:02,635    DEBUG]
```

**Comment by simplecrm-github** [comment] 2024-12-26 06:04
Hi, this was a problem with the date field issue which has junk data on MySQL db so we removed that junk data and the issue resolved, thanks

**Comment by bakwc** [comment] 2024-12-26 08:53
Still interesting what kind of data was in mysql, I tried different possible dates, but could not reproduce it..

**Closed** 2024-12-28 13:39 UTC
